{% set name = "tafra" %}
{% set version = "1.0.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 280d3d845f7bbd7c6fe3decea5d956c424a0bcbec9e53910fcc9b925f75f941b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - numpy >=1.17
    - typing-extensions
  run:
    - numpy >=1.17
    - python >=3.7
    - typing-extensions

test:
  source_files:
    - test
  imports:
    - tafra
    - test
  commands:
    - pip check
    - pytest --cov=tafra --cov-report=term-missing --hypothesis-show-statistics -v test
  requires:
    - pip
    - pytest
    - hypothesis
    - pytest-cov
    - pandas

about:
  home: https://github.com/petbox-dev/tafra
  summary: 'Tafra: innards of a dataframe'
  license: MIT
  license_file: LICENSE
  description: A minimalist typed dataframe with functional programming concepts.
  doc_url: https://tafra.readthedocs.io
  dev_url: https://github.com/petbox-dev/tafra


extra:
  recipe-maintainers:
    - dsfulf
